FROM node:7.2.0

RUN npm install -g create-react-app
RUN npm install --save react react-dom
RUN npm install --save react-datepicker
RUN npm install --save moment 
RUN npm install --save gh-pages


CMD node && tail -f /dev/null
